### ISSUE TITLE
NOT WORK WHEN TITLE HAVE SPECIAL CHARACTERE

### ISSUE THREAD

**Issue by amnkkn** [altairwei/ZoteroLinkCitation#7]
Thank you for the script, but it does not work when the title contains special characters, such as   '  or other symbols commonly used in different languages.

**Comment by amnkkn** [comment]
Additionally, please create a script to remove all links.
When we execute the macro for the first time, it works. 
But if we add a new citation and try to run the macro again, it does not work, does not link the new citation, and always gives an error.
I think the simplest solution is to remove all links first and then add them again.

**Comment by altairwei** [comment]
> Thank you for the script, but it does not work when the title contains special characters, such as ' or other symbols commonly used in different languages.

Can you provide some examples? So, I can sanitized these special symbols in codes.

**Comment by amnkkn** [comment]
![Image](https://github.com/user-attachments/assets/2a6cec4d-f3ed-4044-b87f-9c347b09c126)
heres is an exemmple 
L’Impact Du climat D’Investissement Sur L’Incitation Des Investissements Directs à l’Etranger: Les Nouvelles Réformes Au Maroc. International Journal of Strategic Management and Economic Studies (IJSMES), 2(6), Article 6. 

this not work because of the special character ' in the title

**Comment by altairwei** [comment]
I checked and it's not `’` that's causing the problem, it's the fact that the title contains a special whitespace character. I have solved this problem by ignores all white space and control characters between words when searching.

**Comment by amnkkn** [comment]
thank you verry much 
you are the best

**Comment by amnkkn** [comment]
Same problem! Please try again using this link:

https://zenodo.org/records/10252781
or this 
https://www.revuechercheur.com/index.php/home/article/view/143

 It’s still not working.


![Image](https://github.com/user-attachments/assets/c14ca1ab-f303-42b6-86ed-8472fc31c24d)

**Comment by altairwei** [comment]
> Same problem! Please try again using this link:
> 
> https://zenodo.org/records/10252781 or this https://www.revuechercheur.com/index.php/home/article/view/143
> 
> It’s still not working.
> 
> ![Image](https://github.com/user-attachments/assets/c14ca1ab-f303-42b6-86ed-8472fc31c24d)

I'm pretty sure this has been fixed. The two links you gave me oh I also tested them again and was able to work. From your picture, I picked up on the fact that you may have manually changed the title of the reference by removing the space before the colon. Please try reinserting the bibliography.

**Comment by amnkkn** [comment]
It's still not working for me; I'm still facing the same problem.

**Comment by altairwei** [comment]
> It's still not working for me; I'm still facing the same problem.

Upload your document to me.

**Comment by amnkkn** [comment]
https://zenodo.org/records/10252781
https://www.revuechercheur.com/index.php/home/article/view/143
i used the chrome extension 
[Zotero Connector](https://chromewebstore.google.com/detail/zotero-connector/ekhagklcjbdpajgpjgmbionohlpdbjgc)

**Comment by altairwei** [comment]
> https://zenodo.org/records/10252781 https://www.revuechercheur.com/index.php/home/article/view/143 i used the chrome extension [Zotero Connector](https://chromewebstore.google.com/detail/zotero-connector/ekhagklcjbdpajgpjgmbionohlpdbjgc)

I'm pretty sure this has been fixed. I also tested the two links you gave me and they worked. From your picture, I picked up on the fact that you may have manually changed the title of the reference by removing the space before the colon. Please try reinserting the bibliography.

**Comment by altairwei** [comment]
If you are not willing to provide documentation for testing purposes. I'll close this issue.

**Comment by amnkkn** [comment]
[mylibrary.zip](https://github.com/user-attachments/files/19091018/mylibrary.zip)
here you can find my lobrary 
please import the tets for.rdf file to your zotero its withouts pdfs 
or ou can import the second file in the folder with pdfs

**Comment by amnkkn** [comment]
Please try with any one of the files I provided,,, none of them are working

**Comment by altairwei** [comment]
> [mylibrary.zip](https://github.com/user-attachments/files/19091018/mylibrary.zip) here you can find my lobrary please import the tets for.rdf file to your zotero its withouts pdfs or ou can import the second file in the folder with pdfs

![Image](https://github.com/user-attachments/assets/3dbead99-bb49-425f-b8c5-bf4e64431daf)

See? Everything is working fine. If you really want to solve this problem, make a word document on your computer and send it to me.

**Comment by amnkkn** [comment]
omg its work for you .. i dont understand why its not for me

**Comment by altairwei** [comment]
> [test .docx](https://github.com/user-attachments/files/19095861/test.docx)

![Image](https://github.com/user-attachments/assets/86247fc2-f058-4958-90fc-e10df96aaab9)

I made a graph to show the problem you have with this document. The first line is your Zotero built-in citation data, and the second line is the text in bibliography. As you can see, your bibliography text has been modified so that it doesn't match the Zotero built-in data, which is why ZoteroLinkCitation doesn't work.

What can you do? Delete the entire bibliography and let Zotero reinsert a new bibliography that matches the embedded data.

**Comment by amnkkn** [comment]
Please see the video that i sent you in your email adress yesterday. Please check your email 

I already add new citation and new biblioghraohy and   lines befor text citation but still not working
or please if we can do  remote desktop meeting  and fix the problem for me.

Here's the video that i sent you in your email 
https://drive.google.com/file/d/1tcZm8pMA3boUfBPRndf4thvm6eOiSDXI/view?pli=1

**Comment by amnkkn** [comment]
> > [mylibrary.zip](https://github.com/user-attachments/files/19091018/mylibrary.zip) here you can find my lobrary please import the tets for.rdf file to your zotero its withouts pdfs or ou can import the second file in the folder with pdfs
> 
> ![Image](https://github.com/user-attachments/assets/3dbead99-bb49-425f-b8c5-bf4e64431daf)
> 
> See? Everything is working fine. If you really want to solve this problem, make a word document on your computer and send it to me.

Please try APA style

**Comment by altairwei** [comment]
> Please try APA style

Well, it looks like the APA is causing the problem, I'll look into it.

**Comment by altairwei** [comment]
![Image](https://github.com/user-attachments/assets/07b046d9-eb6c-473f-a0e3-d04d32237059)

@amnkkn Changing the referencing language of your document to French will solve the APA style problem.

**Comment by altairwei** [comment]
> Additionally, please create a script to remove all links.

This can be done by switching the Zotero reference format back and forth to refresh the entire document and all links will be automatically removed.
